using 1.5.2 instead of 1.5.3 because of flag deprecations

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,4 +1,13 @@
 #! /bin/bash
+#
+# Flywheel 2017
+#
+#
+
+
+################################################################################
+# DEFINE VARIABLES
+
 FLYWHEEL_BASE=/flywheel/v0
 MANIFEST_FILE=$FLYWHEEL_BASE/manifest.json
 CONFIG_FILE=$FLYWHEEL_BASE/config.json
@@ -7,11 +16,27 @@ INPUT_DIR=$FLYWHEEL_BASE/input
 GEAR_OUTPUT_DIR=$FLYWHEEL_BASE/output
 FMRIPREP_OUTPUT_DIR=$GEAR_OUTPUT_DIR/"$ANALYSIS_ID"
 WORKING_DIR=$GEAR_OUTPUT_DIR/"$ANALYSIS_ID"_work
+FREESURFER_LICENSE_DIR=$INPUT_DIR/freesurfer_license
 BIDS_DIR=$GEAR_OUTPUT_DIR/bids_dataset
 CONTAINER='[flywheel/fmriprep]'
 
-cat ${FLYWHEEL_BASE}/docker-env.sh
+
+################################################################################
+# DISPLAY FMRIPREP DOCKERFILE FOR BUILD INFO
+
+echo -e "$CONTAINER BEGIN FMRIPREP DOCKERFILE\n"
+cat ${FLYWHEEL_BASE}/*Dockerfile
+echo -e "$CONTAINER END FMRIPREP DOCKERFILE \n"
+
+
+################################################################################
+# CONFIGURE ENV
+
 source ${FLYWHEEL_BASE}/docker-env.sh
+
+
+##############################################################################
+# Parse configuration
 
 function parse_config {
 
@@ -31,26 +56,294 @@ config_save_intermediate_work="$(parse_config 'save_intermediate_work')"
 config_intermediate_files="$(parse_config 'intermediate_files')"
 config_intermediate_folders="$(parse_config 'intermediate_folders')"
 
+##################
+# Workflow Options
+config_ignore="$(parse_config 'ignore')"
+config_anat_only="$(parse_config 'anat_only')"
+config_longitudinal="$(parse_config 'longitudinal')"
+config_t2s_coreg="$(parse_config 't2s_coreg')"
+config_bold2t1w_dof="$(parse_config 'bold2t1w_dof')"
+config_output_space="$(parse_config 'output_space')"
+config_force_bbr="$(parse_config 'force_bbr')"
+config_force_no_bbr="$(parse_config 'force_no_bbr')"
+config_template="$(parse_config 'template')"
+config_template_resampling_grid="$(parse_config 'template_resampling_grid')"
+config_medial_surface_nan="$(parse_config 'medial_surface_nan')"
+config_sloppy_mode="$(parse_config 'sloppy_mode')"
 
-echo -e "$CONTAINER BEGIN FMRIPREP DOCKERFILE\n"
-cat ${FLYWHEEL_BASE}/*Dockerfile
-echo -e "$CONTAINER END FMRIPREP DOCKERFILE \n"
+
+template_FLAG='--template '${config_template}
+template_resampling_grid_FLAG='--template-resampling-grid '${config_template_resampling_grid}
+bold2t1w_dof_FLAG='--bold2t1w-dof '${config_bold2t1w_dof}
+output_space_FLAG='--output-space '${config_output_space}
+
+if [[ $config_ignore == '' ]]; then
+  ignore_FLAG=''
+else
+  ignore_FLAG='--ignore '${config_ignore}
+fi
+
+if [[ $config_longitudinal == 'false' ]]; then
+  longitudinal_FLAG=''
+else
+  longitudinal_FLAG='--longitudinal'
+fi
+
+if [[ $config_anat_only == 'false' ]]; then
+  anat_only_FLAG=''
+else
+  anat_only_FLAG='--anat-only'
+fi
+
+if [[ $config_t2s_coreg == 'false' ]]; then
+  t2s_coreg_FLAG=''
+else
+  t2s_coreg_FLAG='--t2s-coreg'
+fi
+
+if [[ $config_force_bbr == 'false' ]]; then
+  force_bbr_FLAG=''
+else
+  force_bbr_FLAG='--force-bbr'
+fi
+
+if [[ $config_force_no_bbr == 'false' ]]; then
+  force_no_bbr_FLAG=''
+else
+  force_no_bbr_FLAG='--force-no-bbr'
+fi
+
+if [[ $config_medial_surface_nan == 'false' ]]; then
+  medial_surface_nan_FLAG=''
+else
+  medial_surface_nan_FLAG='--medial-surface-nan'
+fi
 
 
-# Download BIDS data and write a command
-/usr/local/miniconda/bin/python /flywheel/v0/prepare_run.py
-PREPARATION_EXIT_STATUS=$?
-if [[ $PREPARATION_EXIT_STATUS -gt 0 ]]; then
-  echo "$CONTAINER Unable to download BIDS data! Exiting"
+##################
+# Specific options for ICA Aroma
+config_use_aroma="$(parse_config 'use_aroma')"
+config_aroma_melodic_dimensionality="$(parse_config 'aroma_melodic_dimensionality')"
+
+if [[ $config_use_aroma == 'false' ]]; then
+  use_aroma_FLAG=''
+else
+  use_aroma_FLAG='--use-aroma'
+fi
+
+if [[ $config_aroma_melodic_dimensionality == 'None' ]]; then
+  aroma_melodic_dimensionality_FLAG=''
+else
+  aroma_melodic_dimensionality_FLAG='--aroma-melodic-dimensionality '"${config_aroma_melodic_dimensionality}"
+fi
+
+
+##################
+# Specific options for ANTs registrations
+config_skull_strip_template="$(parse_config 'skull_strip_template')"
+config_skull_strip_fixed_seed="$(parse_config 'skull_strip_fixed_seed')"
+
+skull_strip_template_FLAG='--skull-strip-template '${config_skull_strip_template}
+
+if [[ $config_skull_strip_fixed_seed == 'false' ]]; then
+  skull_strip_fixed_seed_FLAG=''
+else
+  skull_strip_fixed_seed_FLAG='--skull-strip-fixed-seed'
+fi
+
+##################
+# Specific options for fieldmaps
+config_fmap_bspline="$(parse_config 'fmap_bspline')"
+config_fmap_no_demean="$(parse_config 'fmap_no_demean')"
+
+if [[ $config_fmap_bspline == 'false' ]]; then
+  fmap_bspline_FLAG=''
+else
+  fmap_bspline_FLAG='--fmap-bspline'
+fi
+
+if [[ $config_fmap_no_demean == 'false' ]]; then
+  fmap_no_demean_FLAG=''
+else
+  fmap_no_demean_FLAG='--fmap-no-demean'
+fi
+
+##################
+# Specific options for SyN distortion correction
+config_use_syn_sdc="$(parse_config 'use_syn_sdc')"
+config_force_syn="$(parse_config 'force_syn')"
+
+if [[ $config_use_syn_sdc == 'false' ]]; then
+  use_syn_sdc_FLAG=''
+else
+  use_syn_sdc_FLAG='--use-syn-sdc'
+fi
+
+if [[ $config_force_syn == 'false' ]]; then
+  force_syn_FLAG=''
+else
+  force_syn_FLAG='--force-syn'
+fi
+
+##################
+# Surface preprocessing options
+config_no_submm_recon="$(parse_config 'no_submm_recon')"
+config_cifti_output="$(parse_config 'cifti_output')"
+config_freesurfer="$(parse_config 'fs_no_reconall')"
+
+if [[ $config_no_submm_recon == 'false' ]]; then
+  no_submm_recon_FLAG=''
+else
+  no_submm_recon_FLAG='--no-submm-recon'
+fi
+
+if [[ $config_cifti_output == 'false' ]]; then
+  cifti_output_FLAG=''
+else
+  cifti_output_FLAG='--cifti-output'
+fi
+
+# Boolean parsing of freesurfer config option
+if [[ $config_freesurfer == 'false' ]]; then
+  freesurfer_FLAG=''
+else
+  freesurfer_FLAG='--fs-no-reconall'
+fi
+
+################################################################################
+# Sloppy mode
+
+# Boolean parsing of sloppy config option
+if [[ $config_sloppy_mode == 'false' ]]; then
+  sloppy_FLAG=''
+else
+  sloppy_FLAG='--sloppy'
+fi
+
+################################################################################
+# Freesurfer License
+
+########################
+
+echo "$CONTAINER  Attempting to generate license file..."
+
+need_license=1
+
+# OPTION 1:  User-Provided license file
+if [[ -d "$FREESURFER_LICENSE_DIR" ]]; then
+  fs_file=$(find $FREESURFER_LICENSE_DIR/* -type f | head -1)
+  if [[ -n "$fs_file" ]]; then
+    echo "    -->Generating FREESURFER LICENSE file from $fs_file"
+    LICENSE_FILE="$fs_file"
+    need_license=0
+  fi
+fi
+
+# Other options handled in parse config...
+if [[ $need_license == 1 ]]; then
+  /usr/local/miniconda/bin/python $FLYWHEEL_BASE/fs_license.py --json_file=${CONFIG_FILE}
+  if [[ $? != 0 ]]; then
+    echo "$CONTAINER  Problem generating FreeSurfer License! Exiting(1)"
+    exit 1
+  fi
+fi
+
+################################################################################
+# CREATE A BIDS FORMATTED DIRECTORY
+#   Use fw-heudiconv to accomplish this task
+
+/usr/local/miniconda/bin/python ${FLYWHEEL_BASE}/create_archive_fw_heudiconv.py
+if [[ $? != 0 ]]; then
+  echo "$CONTAINER  Problem creating archive! Exiting (1)"
+  rm -rf ${BIDS_DIR}
   exit 1
 fi
 
+
+################################################################################
+# VALIDATE INPUT DATA
+# Check if the input directory is not empty
+if [[ "$(ls -A $INPUT_DIR)" ]] ; then
+    echo "$CONTAINER  Starting..."
+else
+    echo "Input directory is empty: $INPUT_DIR"
+    exit 1
+fi
+
+# Show the contents of the BIDS directory
+ls -R ${BIDS_DIR}
+
+################################################################################
 # RUN FMRIPREP
 export NODE_OPTIONS="--max-old-space-size=6000"
-time bash /flywheel/v0/output/fmriprep_run.sh
+echo "Call:"
+echo /usr/local/miniconda/bin/fmriprep \
+      --skip_bids_validation \
+      ${BIDS_DIR} \
+      ${FMRIPREP_OUTPUT_DIR} \
+      participant \
+      -w ${WORKING_DIR} \
+      ${anat_only_FLAG} \
+      ${freesurfer_FLAG} \
+      ${ignore_FLAG} \
+      ${longitudinal_FLAG} \
+      ${t2s_coreg_FLAG} \
+      ${bold2t1w_dof_FLAG} \
+      ${output_space_FLAG} \
+      ${force_bbr_FLAG} \
+      ${force_no_bbr_FLAG} \
+      ${template_FLAG} \
+      ${template_resampling_grid_FLAG} \
+      ${medial_surface_nan_FLAG} \
+      ${use_aroma_FLAG} \
+      ${aroma_melodic_dimensionality_FLAG} \
+      ${skull_strip_template_FLAG} \
+      ${skull_strip_fixed_seed_FLAG} \
+      ${fmap_bspline_FLAG} \
+      ${fmap_no_demean_FLAG} \
+      ${use_syn_sdc_FLAG} \
+      ${force_syn_FLAG} \
+      ${no_submm_recon_FLAG} \
+      ${cifti_output_FLAG} \
+      ${sloppy_FLAG} \
+      --fs-license-file ${LICENSE_FILE}
+time /usr/local/miniconda/bin/fmriprep \
+      --skip_bids_validation \
+      ${BIDS_DIR} \
+      ${FMRIPREP_OUTPUT_DIR} \
+      participant \
+      -w ${WORKING_DIR} \
+      ${anat_only_FLAG} \
+      ${freesurfer_FLAG} \
+      ${ignore_FLAG} \
+      ${longitudinal_FLAG} \
+      ${t2s_coreg_FLAG} \
+      ${bold2t1w_dof_FLAG} \
+      ${output_space_FLAG} \
+      ${force_bbr_FLAG} \
+      ${force_no_bbr_FLAG} \
+      ${template_FLAG} \
+      ${template_resampling_grid_FLAG} \
+      ${medial_surface_nan_FLAG} \
+      ${use_aroma_FLAG} \
+      ${aroma_melodic_dimensionality_FLAG} \
+      ${skull_strip_template_FLAG} \
+      ${skull_strip_fixed_seed_FLAG} \
+      ${fmap_bspline_FLAG} \
+      ${fmap_no_demean_FLAG} \
+      ${use_syn_sdc_FLAG} \
+      ${force_syn_FLAG} \
+      ${no_submm_recon_FLAG} \
+      ${cifti_output_FLAG} \
+      ${sloppy_FLAG} \
+      --fs-license-file ${LICENSE_FILE}
+
 
 FMRIPREP_EXITSTATUS=$?
 
+
+################################################################################
+# CLEANUP OUTPUTS
 rm -rf "$BIDS_DIR"
 
 if [[ $FMRIPREP_EXITSTATUS == 0 ]] ; then
